// This file contains collection of widgets and content items, used in AppFactory
{$IFDEF WidgetsSupport}
  ContentCollection in '..\Source\ContentCollection.pas',
  Widgets in '..\Source\Widgets.pas',
{$ENDIF}
  wuBrowser in '..\Widgets\wuBrowser.pas',
  wuImage in '..\Widgets\wuImage.pas',
  wuMap in '..\Widgets\wuMap.pas',
  wuText in '..\Widgets\wuText.pas',
  wuContact in '..\Widgets\wuContact.pas'
